---
defaults:
  - _self_
  - preprocess: preprocess
  - train: train
  - evaluate: evaluate
  - secrets: secret

###
# Common parameters
###
train_only: false
model_name: OBPointSeq2Seq
scaling_method: min_max_standard
weights_initializer: he
is_obpoint_labeldata: true

multi_parameters_model:
  return_sequences: true # If true, out_channels is set to 1 (only rain) and sequental_evalaution is not run. If false, seuqential_evaluation is run.
single_parameter_model:
  return_sequences: true

debug_mode: false
use_dummy_data: false

###
# Tensor shape information
###
input_seq_length: 6
label_seq_length: 6
tensor_height: 50
tensor_width: 50

# NOTE: you cannot list parameters of hydra with mlflow.run.parameters.
# shlex.quote used in mlflow to parse run parameters.
# and this method doesnt parse list literal `[]`.
input_parameters: rain/temperature/humidity

###
# Path info
###
pipeline_root_dir_path: /home/akira/Desktop/p-poteka/ppoteka-rainfall-prediction/poteka-pipeline-pytorch

###
# Hydra settings
# Disable output directory
###
hydra:
  output_subdir: null
  run:
    dir: .
