use_test_model: true
downstream_dir_path: ../data/train/
upstream_dir_path: null # overrided in mlflow training process.

# Training parameters
epochs: 500
batch_size: 4
optimizer_learning_rate: 0.0005

# Early stopping settings
earlystopping:
  patience: 500
  verbose: true
  delta: 0.0001

# Other parameters
train_separately: false
is_max_datasize_limit: false
loss_only_rain: false

# Model parameters
seq_to_seq:
  kernel_size: 3
  num_kernels: 64
  padding: same
  activation: leakyRelu
  num_layers: 4
  
self_attention:
  attention_hidden_dims: 4
